ext/webadmin/server/Controllers/AuthController.cs
using System.Collections.Generic;
using System.Dynamic;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using static CitizenFX.Core.Native.API;

namespace FxWebAdmin
{
    public class AuthController : Controller
    {
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public IActionResult LoginThirdParty([FromForm] string source)
        {
            if (source == "steam" || source == "discourse")
            {
                return Challenge(new AuthenticationProperties()
                {
                    RedirectUri = "/webadmin/"
                }, source);
            }

            return Forbid();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> LoginRcon([FromForm] string password)
        {
            var passwordVar = GetConvar("rcon_password", "");

            if (string.IsNullOrWhiteSpace(passwordVar))
            {
                ViewBag.Error = "Invalid RCON password.";

                return View("Login");
            }

            if (password != passwordVar)
            {
                ViewBag.Error = "Invalid RCON password.";

                return View("Login");
            }

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, "System Console"),
                new Claim(ClaimTypes.NameIdentifier, "https://cfx.re/id/rcon"),
                new Claim("cfx:rcon_password", password)
            };

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties()
            {
                RedirectUri = "/webadmin/"
            };
            
            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                authProperties);

            return Redirect("/webadmin/");
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(new AuthenticationProperties());

            return Redirect("/webadmin/");
        }
    }
}

ext/webadmin/server/Controllers/ConsoleController.cs
using CitizenFX.Core.Native;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FxWebAdmin
{
    public class ConsoleController : Controller
    {
        public ConsoleController(ConsoleLog log)
        {

        }

        [Authorize(Roles = "webadmin.console.read")]
        public IActionResult Log()
        {
            return View(
                (object)API.GetConsoleBuffer()
            );
        }
    }
}

ext/webadmin/server/Controllers/ResourcesController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

using static CitizenFX.Core.Native.API;

namespace FxWebAdmin
{
    public class ResourcesController : Controller
    {
        [Authorize(Roles = "command.start,command.restart,command.stop,webadmin.resources.view")]
        [HttpGet]
        public IActionResult List()
        {
            return View(new ResourcesData());
        }

        [Authorize(Roles = "command.refresh,webadmin.resources.refresh")]
        [HttpPost]
        public async Task<IActionResult> Refresh()
        {
            await HttpServer.QueueTick(() =>
            {
                // TODO: access control for this(!)
                ExecuteCommand("refresh");
            });

            return RedirectToAction("List");
        }

        [Authorize(Roles = "command.start,webadmin.resources.start")]
        [HttpPost]
        public async Task<IActionResult> Start([FromForm] string resource)
        {
            var success = await HttpServer.QueueTick(() =>
            {
                return StartResource(resource);
            });

            HttpContext.Session.Set("alert", (success) ?
                new Alert(AlertType.Success, $"{resource} has been successfully started.") :
                new Alert(AlertType.Danger, $"{resource} failed to start immediately. See the server console for details."));

            return RedirectToAction("List");
        }

        [Authorize(Roles = "command.stop,webadmin.resources.stop")]
        [HttpPost]
        public async Task<IActionResult> Stop([FromForm] string resource)
        {
            if (resource != "webadmin")
            {
                var success = await HttpServer.QueueTick(() =>
                {
                    return StopResource(resource);
                });

                HttpContext.Session.Set("alert", (success) ?
                    new Alert(AlertType.Success, $"{resource} has been successfully stopped.") :
                    new Alert(AlertType.Danger, $"{resource} failed to stop. See the server console for details."));
            }

            return RedirectToAction("List");
        }

        [Authorize(Roles = "command.restart,webadmin.resources.restart")]
        [HttpPost]
        public async Task<IActionResult> Restart([FromForm] string resource)
        {
            if (resource != "webadmin")
            {
                var success = await HttpServer.QueueTick(() =>
                {
                    if (StopResource(resource))
                    {
                        return StartResource(resource);
                    }

                    return false;
                });

                HttpContext.Session.Set("alert", (success) ?
                    new Alert(AlertType.Success, $"{resource} has been successfully restarted.") :
                    new Alert(AlertType.Danger, $"{resource} failed to restart immediately. See the server console for details."));
            }

            return RedirectToAction("List");
        }
    }

    public class ResourcesData
    {
        public IEnumerable<string> GetResources()
        {
            for (int i = 0; i < GetNumResources(); i++)
            {
                var resourceName = GetResourceByFindIndex(i);

                if (resourceName == "webadmin" || resourceName == "_cfx_internal")
                {
                    continue;
                }

                yield return resourceName;
            }
        }

        public IEnumerable<string> GetMetadata(string resource, string kind)
        {
            for (int i = 0; i < GetNumResourceMetadata(resource, kind); i++)
            {
                yield return GetResourceMetadata(resource, kind, i);
            }
        }
    }
}

ext/webadmin/server/Views/Shared/_Header.cshtml
<header class="app-header navbar">
  <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">
    FXServer
  </a>

  @await Html.PartialAsync("_HeaderNav.cshtml")

  @if (User?.Identity?.IsAuthenticated ?? false)
  {
    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link px-3" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                @User.Identity.Name
                <img class="img-avatar" src='@(User.FindFirst("cfx:avatar")?.Value ?? "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8DwHwAFBQIAX8jx0gAAAABJRU5ErkJggg==")'>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-header text-center">
                    <strong>Account</strong>
                </div>
                <form asp-controller="Auth" asp-action="Logout" method="post" id="logoutForm">
                    <script>
                    function logout() {
                        $('#logoutForm').submit();
                    }
                    </script>
                    <a class="dropdown-item" href="javascript: void(0)" onclick="logout()">
                    <i class="fa fa-lock"></i> Logout
                    </a>
                </form>

            </div>
        </li>
    </ul>
  }
  else
  {
    <ul class="nav navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link px-3" asp-controller="Auth" asp-action="Login" role="button">
                Login
            </a>
        </li>
    </ul>   
  }

</header>

ext/webadmin/server/Views/Shared/_HeaderNav.cshtml
<ul class="nav navbar-nav d-md-down-none">
    <li class="nav-item px-3">
        <a href="~/">Home</a>
    </li>
    <cfx-plugin-outlet name="nav/topList"></cfx-plugin-outlet>
</ul>

ext/webadmin/server/Views/Shared/_Layout.cshtml
@{
    Layout = "_LayoutBase";
}
@using CitizenFX.Core.Native
@using Microsoft.AspNetCore.Http
@using FxWebAdmin

@section page
{
@await Html.PartialAsync("_Header.cshtml")

<div class="app-body">
<div class="sidebar">
@await Html.PartialAsync("_SidebarNav.cshtml")

<button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>
<main class="main">
<div class="container-fluid">
@if (Context.Session.GetString("alert") != null)
{
    var alert = Context.Session.Get<Alert>("alert");
    Context.Session.Remove("alert");
    
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 my-2">
                <div class="@alert.Class" role="alert">
                    @(alert.Text)
                </div>
            </div>
        </div>
    </div>
}

@await FlushAsync()
@RenderBody()
@await RenderSectionAsync("content", false)
</div>
</main>

</div>
<footer class="app-footer">
<div>
@API.GetConvar("version", "")
</div>
<div class="ml-auto">
<span>Powered by</span>
<a href="https://coreui.io">CoreUI</a>
</div>
</footer>
}

ext/webadmin/server/Views/Shared/_LayoutBase.cshtml
@using CitizenFX.Core.Native

<!doctype html>
<!html lang="en">
<!head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<base href="/webadmin/">

<link rel="shortcut icon" href="icon.png">
<link rel="stylesheet" href="css/bootstrap.min.css">
<link rel="stylesheet" href="css/coreui.min.css">
<link rel="stylesheet" href="css/fontawesome.min.css">
<link rel="stylesheet" href="css/flag-icon.min.css">

<title>@ViewData["Title"] - @API.GetConvar("sv_hostname", "")</title>
</!head>
<!body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show bg-gray-200">
@RenderBody()
@await FlushAsync()
@await RenderSectionAsync("page", false)

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="js/coreui.min.js" crossorigin="anonymous"></script>

@RenderSection("Scripts", required: false)
</!body>
</!html>

ext/webadmin/server/Views/Shared/_SidebarNav.cshtml
<nav class="sidebar-nav">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="~/" asp-active-controllers="Home" asp-active-actions="Index">
                <i class="nav-icon fa fa-home"></i> Home
            </a>
        </li>
        @if ((User?.IsInRole("command.start") ?? false) || (User?.IsInRole("command.stop") ?? false) ||
           (User?.IsInRole("command.restart") ?? false) || (User?.IsInRole("webadmin.resources.view") ?? false))
        {
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Resources" asp-action="List" asp-active-controllers="Resources" asp-active-actions="List">
                    <i class="nav-icon fa fa-plug"></i> Resources
                </a>
            </li>
        }
        @if ((User?.IsInRole("webadmin.console.read") ?? false))
        {
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Console" asp-action="Log" asp-active-controllers="Console" asp-active-actions="Log">
                    <i class="nav-icon fa fa-terminal"></i> Console
                </a>
            </li>
        }
        <cfx-plugin-outlet name="nav/sideList"></cfx-plugin-outlet>
    </ul>
</nav>